# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self

class CheckpointManager:
    def __init__(self: Self, kernel: Any) -> None: ...
    def save(self: Self, context_id: str, node_id: str, payload: dict, node_name: str) -> Any: ...
    def load(self: Self, context_id: str) -> Any: ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
