# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
from utils.type_converter import to_number
import random
import time

class LoopHandler:
    def __init__(self: Self, kernel: Any, core_executor_func: Any) -> None: ...
    def execute_with_loop(self: Self, payload: dict, config: dict, node_info: dict, context_id: str, mode: str) -> Any: ...
    def _check_condition(self: Self, payload: dict, config: dict) -> bool: ...
    def _handle_sleep(self: Self, config: dict, node_name: str, mode: str) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import time
import random