# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
import time

class RetryHandler:
    def __init__(self: Self, kernel: Any, core_executor_func: Any) -> None: ...
    def execute_with_retries(self: Self, payload: dict, config: dict, node_info: dict, context_id: str, mode: str) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import time