# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
import re

class VariableResolver:
    def __init__(self: Self, kernel: Any) -> None: ...
    def resolve(self: Self, config_item: any) -> any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import re