# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from typing import Any
from typing_extensions import Self
import json
import os
import threading

class StateManagerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def load_state(self: Self) -> Any: ...
    def _save_state_to_file(self: Self) -> Any: ...
    def get(self: Self, key: Any, default: Any) -> Any: ...
    def set(self: Self, key: Any, value: Any) -> Any: ...
    def delete(self: Self, key: Any) -> Any: ...
    def get_all(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import json
import threading
import ntpath