# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from typing import Any
from typing_extensions import Self
import hashlib
import json
import os

class IntegrityCheckerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def _calculate_sha256(self: Self, file_path: Any) -> Any: ...
    def verify_core_files(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import json
import hashlib
import ntpath