# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base_service import BaseService
from flowork_kernel.models.AgentModel import AgentModel
from typing import Any
from typing_extensions import Self
import uuid

class AgentManagerService(BaseService):
    def __init__(self: Self, kernel: Any, service_id: str) -> None: ...
    def get_all_agents(self: Self) -> list[dict]: ...
    def get_agent(self: Self, agent_id: str) -> dict | None: ...
    def save_agent(self: Self, agent_data: dict) -> dict: ...
    def delete_agent(self: Self, agent_id: str) -> bool: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flowork_kernel
import flowork_kernel.models
import flowork_kernel.models.AgentModel
import uuid